# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Pegelonline
                                 A QGIS plugin
 Access and display the data of "pegelonline.wsv.de"
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-30
        copyright            : (C) 2021 by Andreas Müller
        email                : muellea@uni-trier.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Pegelonline class from file Pegelonline.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pegelonline import Pegelonline
    return Pegelonline(iface)
